CREATE TABLE IF NOT EXISTS customer_groups (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(140) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 company VARCHAR(190) NOT NULL DEFAULT '', role ENUM('customer','staff') NOT NULL DEFAULT 'customer',
 group_id INT UNSIGNED NOT NULL DEFAULT 1, status ENUM('active','pending','blocked') NOT NULL DEFAULT 'pending',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(group_id) REFERENCES customer_groups(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS reset_tokens (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, user_id INT UNSIGNED NOT NULL,
 token_hash CHAR(64) NOT NULL UNIQUE, expires_at DATETIME NOT NULL, used_at DATETIME NULL,
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS login_attempts (
 fingerprint CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 0, last_attempt DATETIME NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS categories (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(140) NOT NULL, slug VARCHAR(190) NOT NULL UNIQUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS brands (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(140) NOT NULL UNIQUE
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS device_models (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, brand_id INT UNSIGNED NOT NULL, name VARCHAR(190) NOT NULL,
 UNIQUE(brand_id,name), FOREIGN KEY(brand_id) REFERENCES brands(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS products (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sku VARCHAR(190) NOT NULL UNIQUE, name VARCHAR(500) NOT NULL,
 description TEXT NOT NULL, category_id INT UNSIGNED NULL, brand_id INT UNSIGNED NULL,
 quality VARCHAR(100) NOT NULL DEFAULT '', stock INT UNSIGNED NOT NULL DEFAULT 0,
 list_price_cents INT UNSIGNED NOT NULL DEFAULT 0, minimum_quantity INT UNSIGNED NOT NULL DEFAULT 1,
 image_url VARCHAR(500) NOT NULL DEFAULT '', featured TINYINT NOT NULL DEFAULT 0, active TINYINT NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(category_id),INDEX(brand_id),INDEX(active,featured),INDEX(name(100)),
 FOREIGN KEY(category_id) REFERENCES categories(id), FOREIGN KEY(brand_id) REFERENCES brands(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS product_models (
 product_id INT UNSIGNED NOT NULL, model_id INT UNSIGNED NOT NULL, PRIMARY KEY(product_id,model_id),
 FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(model_id) REFERENCES device_models(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS group_prices (
 product_id INT UNSIGNED NOT NULL, group_id INT UNSIGNED NOT NULL, price_cents INT UNSIGNED NOT NULL,
 PRIMARY KEY(product_id,group_id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(group_id) REFERENCES customer_groups(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS images (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id INT UNSIGNED NOT NULL,
 url VARCHAR(500) NOT NULL, variants JSON NOT NULL, original_path VARCHAR(500) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS addresses (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, user_id INT UNSIGNED NOT NULL,
 label VARCHAR(100) NOT NULL, name VARCHAR(140) NOT NULL, company VARCHAR(190) NOT NULL DEFAULT '',
 line1 VARCHAR(190) NOT NULL,line2 VARCHAR(190) NOT NULL DEFAULT '', postal_code VARCHAR(30) NOT NULL,
 city VARCHAR(100) NOT NULL,country CHAR(2) NOT NULL DEFAULT 'CH', is_default TINYINT NOT NULL DEFAULT 0,
 FOREIGN KEY(user_id) REFERENCES users(id),INDEX(user_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS cart_items (
 user_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,quantity INT UNSIGNED NOT NULL,
 PRIMARY KEY(user_id,product_id), FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS orders (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, number VARCHAR(40) NOT NULL UNIQUE,
 user_id INT UNSIGNED NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'processing',
 subtotal_cents INT UNSIGNED NOT NULL,tax_cents INT UNSIGNED NOT NULL,shipping_cents INT UNSIGNED NOT NULL,total_cents INT UNSIGNED NOT NULL,
 tax_bps INT UNSIGNED NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'CHF', address_json JSON NOT NULL,
 payment_method VARCHAR(30) NOT NULL,notes TEXT NOT NULL,tracking VARCHAR(190) NOT NULL DEFAULT '',
 idempotency_key VARCHAR(100) NOT NULL,stock_restored TINYINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(user_id,idempotency_key),
 FOREIGN KEY(user_id) REFERENCES users(id),INDEX(status)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_items (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,order_id INT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,
 name VARCHAR(500) NOT NULL,sku VARCHAR(190) NOT NULL,quantity INT UNSIGNED NOT NULL,
 price_cents INT UNSIGNED NOT NULL,total_cents INT UNSIGNED NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS order_events (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,order_id INT UNSIGNED NOT NULL,status VARCHAR(30) NOT NULL,note TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(order_id) REFERENCES orders(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS invoice_accounting (
 order_id INT UNSIGNED PRIMARY KEY,verified TINYINT(1) NOT NULL DEFAULT 0,due_date DATE NULL,
 paid_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,note TEXT NOT NULL,version INT UNSIGNED NOT NULL DEFAULT 0,
 updated_by INT UNSIGNED NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(updated_by) REFERENCES users(id),
 INDEX(due_date),INDEX(verified)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS returns (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,number VARCHAR(40) NOT NULL UNIQUE,
 user_id INT UNSIGNED NOT NULL,order_id INT UNSIGNED NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'submitted',
 reason TEXT NOT NULL,credit_cents INT UNSIGNED NOT NULL DEFAULT 0,note TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(order_id) REFERENCES orders(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS return_items (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,return_id INT UNSIGNED NOT NULL,order_item_id INT UNSIGNED NOT NULL,
 quantity INT UNSIGNED NOT NULL,UNIQUE(return_id,order_item_id),
 FOREIGN KEY(return_id) REFERENCES returns(id),FOREIGN KEY(order_item_id) REFERENCES order_items(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS return_events (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,return_id INT UNSIGNED NOT NULL,status VARCHAR(30) NOT NULL,note TEXT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(return_id) REFERENCES returns(id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS messages (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,kind VARCHAR(100) NOT NULL,payload JSON NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'captured',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS audit_events (
 id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,user_id INT UNSIGNED NULL,action VARCHAR(100) NOT NULL,
 entity VARCHAR(100) NOT NULL,entity_id INT UNSIGNED NOT NULL,details JSON NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS settings (
 name VARCHAR(100) PRIMARY KEY,value VARCHAR(500) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS buyback_items (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,model VARCHAR(190) NOT NULL,grade VARCHAR(60) NOT NULL,
 price_cents INT UNSIGNED NOT NULL,active TINYINT NOT NULL DEFAULT 1,UNIQUE(model,grade)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS buyback_requests (
 id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,number VARCHAR(40) NOT NULL UNIQUE,user_id INT UNSIGNED NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'submitted',items_json JSON NOT NULL,total_cents INT UNSIGNED NOT NULL,
 notes TEXT NOT NULL,note TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
) ENGINE=InnoDB;