-- Native PHP parts store, isolated in its own PostgreSQL schema.
CREATE SCHEMA IF NOT EXISTS parts_store;

CREATE TABLE IF NOT EXISTS parts_store.customer_groups (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS parts_store.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(140) NOT NULL,
  email varchar(190) NOT NULL,
  password_hash varchar(255) NOT NULL,
  company varchar(190) NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'customer',
  group_id integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'pending',
  phone varchar(40) NOT NULL DEFAULT '',
  website varchar(255) NOT NULL DEFAULT '',
  business_activity varchar(80) NOT NULL DEFAULT '',
  tax_registration_type varchar(40) NOT NULL DEFAULT '',
  tax_registration_number varchar(80) NOT NULL DEFAULT '',
  newsletter_opt_in boolean NOT NULL DEFAULT false,
  terms_accepted_at timestamptz,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(group_id) REFERENCES parts_store.customer_groups(id)
);

CREATE TABLE IF NOT EXISTS parts_store.reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  token_hash char(64) NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.login_attempts (
  fingerprint char(64) PRIMARY KEY,
  attempts integer NOT NULL DEFAULT 0,
  last_attempt timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS parts_store.sessions (
  id varchar(128) PRIMARY KEY,
  data text NOT NULL,
  last_accessed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parts_store.categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(140) NOT NULL,
  slug varchar(190) NOT NULL
);

CREATE TABLE IF NOT EXISTS parts_store.brands (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(140) NOT NULL
);

CREATE TABLE IF NOT EXISTS parts_store.device_models (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id integer NOT NULL,
  name varchar(190) NOT NULL,
  UNIQUE (brand_id,name),
  FOREIGN KEY(brand_id) REFERENCES parts_store.brands(id)
);

CREATE TABLE IF NOT EXISTS parts_store.products (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku varchar(190) NOT NULL,
  name varchar(500) NOT NULL,
  description text NOT NULL,
  category_id integer,
  brand_id integer,
  quality varchar(100) NOT NULL DEFAULT '',
  stock integer NOT NULL DEFAULT 0,
  list_price_cents integer NOT NULL DEFAULT 0,
  purchase_price_eur_cents integer,
  list_price_eur_cents integer,
  pricing_version integer NOT NULL DEFAULT 0,
  minimum_quantity integer NOT NULL DEFAULT 1,
  image_url varchar(500) NOT NULL DEFAULT '',
  image_review_required boolean NOT NULL DEFAULT false,
  featured boolean NOT NULL DEFAULT false,
  publication_status text NOT NULL DEFAULT 'draft',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  FOREIGN KEY(category_id) REFERENCES parts_store.categories(id),
  FOREIGN KEY(brand_id) REFERENCES parts_store.brands(id)
);

CREATE TABLE IF NOT EXISTS parts_store.product_models (
  product_id integer NOT NULL,
  model_id integer NOT NULL,
  PRIMARY KEY(product_id,model_id),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id),
  FOREIGN KEY(model_id) REFERENCES parts_store.device_models(id)
);

CREATE TABLE IF NOT EXISTS parts_store.product_model_sources (
  product_id integer NOT NULL,
  model_id integer NOT NULL,
  source text NOT NULL,
  evidence varchar(500) NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(product_id,model_id,source),
  FOREIGN KEY(product_id,model_id) REFERENCES parts_store.product_models(product_id,model_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS parts_store.group_prices (
  product_id integer NOT NULL,
  group_id integer NOT NULL,
  price_cents integer NOT NULL,
  price_eur_cents integer,
  PRIMARY KEY(product_id,group_id),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id),
  FOREIGN KEY(group_id) REFERENCES parts_store.customer_groups(id)
);

CREATE TABLE IF NOT EXISTS parts_store.images (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id integer NOT NULL,
  url varchar(500) NOT NULL,
  variants jsonb NOT NULL,
  original_path varchar(500) NOT NULL,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id)
);

CREATE TABLE IF NOT EXISTS parts_store.addresses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  label varchar(100) NOT NULL,
  name varchar(140) NOT NULL,
  company varchar(190) NOT NULL DEFAULT '',
  line1 text NOT NULL,
  line2 text NOT NULL DEFAULT '',
  postal_code varchar(30) NOT NULL,
  city varchar(100) NOT NULL,
  country char(2) NOT NULL DEFAULT 'CH',
  is_default boolean NOT NULL DEFAULT false,
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.billing_addresses (
  user_id integer PRIMARY KEY,
  label varchar(100) NOT NULL,
  name varchar(140) NOT NULL,
  company varchar(190) NOT NULL DEFAULT '',
  line1 text NOT NULL,
  line2 text NOT NULL DEFAULT '',
  postal_code varchar(30) NOT NULL,
  city varchar(100) NOT NULL,
  country char(2) NOT NULL DEFAULT 'CH',
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.cart_items (
  user_id integer NOT NULL,
  product_id integer NOT NULL,
  quantity integer NOT NULL,
  PRIMARY KEY(user_id,product_id),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id)
);

CREATE TABLE IF NOT EXISTS parts_store.orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number varchar(40) NOT NULL,
  user_id integer NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'on_hold',
  subtotal_cents integer NOT NULL,
  tax_cents integer NOT NULL,
  shipping_cents integer NOT NULL,
  total_cents integer NOT NULL,
  tax_bps integer NOT NULL,
  currency char(3) NOT NULL DEFAULT 'CHF',
  exchange_rate_ppm bigint,
  exchange_rate_date date,
  base_currency char(3),
  address_json jsonb NOT NULL,
  shipping_method_code varchar(40),
  shipping_method_name varchar(100),
  shipping_carrier varchar(60),
  payment_method varchar(30) NOT NULL,
  payment_state varchar(30) NOT NULL DEFAULT 'pending',
  payment_reference_type varchar(4),
  payment_reference varchar(27),
  latest_payment_event_at bigint NOT NULL DEFAULT 0,
  latest_payment_event_id varchar(190) NOT NULL DEFAULT '',
  payment_terms_json jsonb,
  checkout_snapshot jsonb,
  notes text NOT NULL,
  tracking varchar(190) NOT NULL DEFAULT '',
  idempotency_key varchar(100) NOT NULL,
  stock_restored boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now(),
  UNIQUE (user_id,idempotency_key),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.customer_payment_entitlements (
  user_id integer NOT NULL,
  payment_method varchar(30) NOT NULL,
  enabled boolean NOT NULL DEFAULT false,
  granted_by integer,
  granted_at timestamptz,
  revoked_by integer,
  revoked_at timestamptz,
  PRIMARY KEY(user_id,payment_method),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id),
  FOREIGN KEY(granted_by) REFERENCES parts_store.users(id),
  FOREIGN KEY(revoked_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.payment_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL,
  payment_method varchar(30) NOT NULL,
  provider_id varchar(190),
  provider_event_id varchar(190),
  provider_event_created_at bigint NOT NULL DEFAULT 0,
  state varchar(30) NOT NULL,
  payload jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  UNIQUE (provider_event_id),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id)
);

CREATE TABLE IF NOT EXISTS parts_store.order_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL,
  product_id integer NOT NULL,
  name varchar(500) NOT NULL,
  sku varchar(190) NOT NULL,
  quantity integer NOT NULL,
  price_cents integer NOT NULL,
  total_cents integer NOT NULL,
  price_eur_cents integer,
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id)
);

CREATE TABLE IF NOT EXISTS parts_store.order_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL,
  status varchar(30) NOT NULL,
  note text NOT NULL,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id)
);

CREATE TABLE IF NOT EXISTS parts_store.invoice_accounting (
  order_id integer PRIMARY KEY,
  verified boolean NOT NULL DEFAULT false,
  due_date date,
  paid_cents bigint NOT NULL DEFAULT 0,
  note text NOT NULL,
  version integer NOT NULL DEFAULT 0,
  updated_by integer NOT NULL,
  updated_at timestamptz DEFAULT now(),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id),
  FOREIGN KEY(updated_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.imported_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id varchar(190) NOT NULL,
  reference varchar(27) NOT NULL,
  amount_cents bigint NOT NULL,
  currency char(3) NOT NULL,
  booked_at date NOT NULL,
  order_id integer,
  status varchar(30) NOT NULL,
  imported_by integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id),
  FOREIGN KEY(imported_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.returns (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number varchar(40) NOT NULL,
  user_id integer NOT NULL,
  order_id integer NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'submitted',
  reason text NOT NULL,
  credit_cents integer NOT NULL DEFAULT 0,
  note text NOT NULL,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id)
);

CREATE TABLE IF NOT EXISTS parts_store.return_items (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id integer NOT NULL,
  order_item_id integer NOT NULL,
  quantity integer NOT NULL,
  UNIQUE (return_id,order_item_id),
  FOREIGN KEY(return_id) REFERENCES parts_store.returns(id),
  FOREIGN KEY(order_item_id) REFERENCES parts_store.order_items(id)
);

CREATE TABLE IF NOT EXISTS parts_store.return_creation_keys (
  idempotency_key varchar(100) PRIMARY KEY,
  return_id integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(return_id) REFERENCES parts_store.returns(id)
);

CREATE TABLE IF NOT EXISTS parts_store.return_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id integer NOT NULL,
  status varchar(30) NOT NULL,
  note text NOT NULL,
  created_at timestamptz DEFAULT now(),
  FOREIGN KEY(return_id) REFERENCES parts_store.returns(id)
);

CREATE TABLE IF NOT EXISTS parts_store.return_settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id integer NOT NULL,
  idempotency_key varchar(100) NOT NULL,
  kind text NOT NULL,
  status text NOT NULL,
  amount_cents integer NOT NULL,
  currency char(3) NOT NULL,
  provider_reference varchar(190),
  error_message varchar(1000),
  snapshot jsonb NOT NULL,
  created_by integer,
  created_at timestamptz DEFAULT now(),
  settled_at timestamptz,
  UNIQUE (return_id),
  UNIQUE (idempotency_key),
  FOREIGN KEY(return_id) REFERENCES parts_store.returns(id),
  FOREIGN KEY(created_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.customer_credit_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number varchar(60) NOT NULL,
  user_id integer NOT NULL,
  order_id integer NOT NULL,
  return_id integer NOT NULL,
  settlement_id bigint NOT NULL,
  issued_cents integer NOT NULL,
  remaining_cents integer NOT NULL,
  currency char(3) NOT NULL,
  status text NOT NULL DEFAULT 'issued',
  snapshot jsonb NOT NULL,
  created_by integer,
  created_at timestamptz DEFAULT now(),
  UNIQUE (return_id),
  UNIQUE (settlement_id),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id),
  FOREIGN KEY(return_id) REFERENCES parts_store.returns(id),
  FOREIGN KEY(settlement_id) REFERENCES parts_store.return_settlements(id),
  FOREIGN KEY(created_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.credit_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credit_note_id bigint NOT NULL,
  target_order_id integer NOT NULL,
  amount_cents integer NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE (credit_note_id,target_order_id),
  FOREIGN KEY(credit_note_id) REFERENCES parts_store.customer_credit_notes(id),
  FOREIGN KEY(target_order_id) REFERENCES parts_store.orders(id)
);

CREATE TABLE IF NOT EXISTS parts_store.return_item_dispositions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_item_id integer NOT NULL,
  received_quantity integer NOT NULL,
  restock_quantity integer NOT NULL DEFAULT 0,
  disposition text NOT NULL,
  recorded_by integer,
  created_at timestamptz DEFAULT now(),
  UNIQUE (return_item_id),
  FOREIGN KEY(return_item_id) REFERENCES parts_store.return_items(id),
  FOREIGN KEY(recorded_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.return_stock_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_item_id integer NOT NULL,
  product_id integer NOT NULL,
  quantity integer NOT NULL,
  kind text NOT NULL,
  created_by integer,
  created_at timestamptz DEFAULT now(),
  UNIQUE (return_item_id,kind),
  FOREIGN KEY(return_item_id) REFERENCES parts_store.return_items(id),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id),
  FOREIGN KEY(created_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.messages (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind varchar(100) NOT NULL,
  payload jsonb NOT NULL,
  status varchar(30) NOT NULL DEFAULT 'captured',
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parts_store.diagnostics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference varchar(32) NOT NULL,
  severity varchar(20) NOT NULL,
  category varchar(100) NOT NULL,
  summary varchar(1000) NOT NULL,
  context_json jsonb NOT NULL,
  request_method varchar(12),
  request_path varchar(500),
  occurred_at timestamptz NOT NULL DEFAULT now(),
  resolved_at timestamptz,
  resolved_by integer,
  FOREIGN KEY(resolved_by) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer,
  action varchar(100) NOT NULL,
  entity varchar(100) NOT NULL,
  entity_id integer NOT NULL,
  details jsonb NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parts_store.settings (
  name varchar(100) PRIMARY KEY,
  value varchar(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS parts_store.exchange_rates (
  base_currency char(3) NOT NULL,
  quote_currency char(3) NOT NULL,
  rate_ppm bigint NOT NULL,
  rate_date date NOT NULL,
  fetched_at timestamptz NOT NULL,
  source_url varchar(500) NOT NULL,
  PRIMARY KEY(base_currency,quote_currency)
);

CREATE TABLE IF NOT EXISTS parts_store.order_lists (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  name varchar(120) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.order_list_items (
  list_id integer NOT NULL,
  product_id integer NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  added_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(list_id,product_id),
  FOREIGN KEY(list_id) REFERENCES parts_store.order_lists(id) ON DELETE CASCADE,
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id)
);

CREATE TABLE IF NOT EXISTS parts_store.stock_alerts (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  product_id integer NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'waiting',
  created_at timestamptz NOT NULL DEFAULT now(),
  notified_at timestamptz,
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id),
  FOREIGN KEY(product_id) REFERENCES parts_store.products(id)
);

CREATE TABLE IF NOT EXISTS parts_store.billing_preferences (
  user_id integer PRIMARY KEY,
  invoice_email varchar(190) NOT NULL DEFAULT '',
  copy_email varchar(190) NOT NULL DEFAULT '',
  auto_send boolean NOT NULL DEFAULT true,
  reference_label varchar(80) NOT NULL DEFAULT '',
  reference_required boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id)
);

CREATE TABLE IF NOT EXISTS parts_store.invoice_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  order_id integer NOT NULL,
  document_kind varchar(30) NOT NULL DEFAULT 'invoice',
  recipient varchar(190) NOT NULL,
  copy_recipient varchar(190) NOT NULL DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'captured',
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY(user_id) REFERENCES parts_store.users(id),
  FOREIGN KEY(order_id) REFERENCES parts_store.orders(id)
);

CREATE TABLE IF NOT EXISTS parts_store.native_picqer_order_snapshots (
  native_order_id varchar(80) PRIMARY KEY,
  event_id varchar(190) NOT NULL UNIQUE,
  content_hash char(64) NOT NULL,
  order_created_at timestamptz NOT NULL,
  snapshot_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parts_store.native_picqer_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  native_order_id varchar(80) NOT NULL,
  event_id varchar(190) NOT NULL UNIQUE,
  content_hash char(64) NOT NULL,
  order_created_at timestamptz NOT NULL,
  snapshot_json jsonb NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  locked_owner varchar(64),
  locked_until timestamptz,
  last_error varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (native_order_id, content_hash)
);

ALTER TABLE parts_store.orders ADD COLUMN IF NOT EXISTS customer_reference text NOT NULL DEFAULT '';
ALTER TABLE parts_store.products ADD COLUMN IF NOT EXISTS expected_restock_date date;

-- Explicit indexes from the native source (names are schema-local and stable).
CREATE UNIQUE INDEX IF NOT EXISTS customer_groups_name_unique ON parts_store.customer_groups(name);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON parts_store.users(email);
CREATE UNIQUE INDEX IF NOT EXISTS reset_tokens_token_hash_unique ON parts_store.reset_tokens(token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS categories_slug_unique ON parts_store.categories(slug);
CREATE UNIQUE INDEX IF NOT EXISTS brands_name_unique ON parts_store.brands(name);
CREATE UNIQUE INDEX IF NOT EXISTS products_sku_unique ON parts_store.products(sku);
CREATE INDEX IF NOT EXISTS products_category_id_idx ON parts_store.products(category_id);
CREATE INDEX IF NOT EXISTS products_brand_id_idx ON parts_store.products(brand_id);
CREATE INDEX IF NOT EXISTS products_active_publication_featured_idx ON parts_store.products(active, publication_status, featured);
CREATE INDEX IF NOT EXISTS products_name_idx ON parts_store.products(name);
CREATE INDEX IF NOT EXISTS sessions_last_accessed ON parts_store.sessions(last_accessed_at);
CREATE INDEX IF NOT EXISTS addresses_user_id_idx ON parts_store.addresses(user_id);
CREATE INDEX IF NOT EXISTS orders_status_idx ON parts_store.orders(status);
CREATE UNIQUE INDEX IF NOT EXISTS orders_payment_reference_unique ON parts_store.orders(payment_reference);
CREATE INDEX IF NOT EXISTS payment_attempts_order_state_idx ON parts_store.payment_attempts(order_id, state);
CREATE INDEX IF NOT EXISTS payment_attempts_provider_idx ON parts_store.payment_attempts(provider_id);
CREATE INDEX IF NOT EXISTS invoice_accounting_due_date_idx ON parts_store.invoice_accounting(due_date);
CREATE INDEX IF NOT EXISTS invoice_accounting_verified_idx ON parts_store.invoice_accounting(verified);
CREATE INDEX IF NOT EXISTS imported_payments_reference_idx ON parts_store.imported_payments(reference);
CREATE INDEX IF NOT EXISTS imported_payments_order_id_idx ON parts_store.imported_payments(order_id);
CREATE INDEX IF NOT EXISTS customer_credit_notes_user_status_idx ON parts_store.customer_credit_notes(user_id, status);
CREATE INDEX IF NOT EXISTS customer_credit_notes_order_id_idx ON parts_store.customer_credit_notes(order_id);
CREATE INDEX IF NOT EXISTS credit_applications_target_order_idx ON parts_store.credit_applications(target_order_id);
CREATE INDEX IF NOT EXISTS return_stock_movements_product_created_idx ON parts_store.return_stock_movements(product_id, created_at);
CREATE INDEX IF NOT EXISTS diagnostics_occurred_at ON parts_store.diagnostics(occurred_at);
CREATE INDEX IF NOT EXISTS diagnostics_severity_occurred ON parts_store.diagnostics(severity, occurred_at);
CREATE INDEX IF NOT EXISTS diagnostics_category_occurred ON parts_store.diagnostics(category, occurred_at);
CREATE INDEX IF NOT EXISTS diagnostics_reference ON parts_store.diagnostics(reference);
CREATE INDEX IF NOT EXISTS diagnostics_resolution_occurred ON parts_store.diagnostics(resolved_at, occurred_at);
CREATE INDEX IF NOT EXISTS exchange_rates_rate_date_idx ON parts_store.exchange_rates(rate_date);
CREATE UNIQUE INDEX IF NOT EXISTS order_lists_user_name ON parts_store.order_lists(user_id, name);
CREATE INDEX IF NOT EXISTS order_lists_user_updated ON parts_store.order_lists(user_id, updated_at);
CREATE INDEX IF NOT EXISTS order_list_items_product ON parts_store.order_list_items(product_id);
CREATE UNIQUE INDEX IF NOT EXISTS stock_alerts_user_product ON parts_store.stock_alerts(user_id, product_id);
CREATE INDEX IF NOT EXISTS stock_alerts_status_product ON parts_store.stock_alerts(status, product_id);
CREATE UNIQUE INDEX IF NOT EXISTS invoice_deliveries_order_kind ON parts_store.invoice_deliveries(order_id, document_kind);
CREATE INDEX IF NOT EXISTS invoice_deliveries_user_created ON parts_store.invoice_deliveries(user_id, created_at);
CREATE INDEX IF NOT EXISTS native_relay_ready
  ON parts_store.native_picqer_outbox(status, next_attempt_at, locked_until);

-- PostgreSQL has no MySQL ENUM; retain the native value domains as guarded checks.
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_role_check') THEN
    ALTER TABLE parts_store.users ADD CONSTRAINT users_role_check CHECK (role IN ('customer','staff'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_status_check') THEN
    ALTER TABLE parts_store.users ADD CONSTRAINT users_status_check CHECK (status IN ('active','pending','blocked'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'products_publication_status_check') THEN
    ALTER TABLE parts_store.products ADD CONSTRAINT products_publication_status_check CHECK (publication_status IN ('draft','visible'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'product_model_sources_source_check') THEN
    ALTER TABLE parts_store.product_model_sources ADD CONSTRAINT product_model_sources_source_check CHECK (source IN ('source_taxonomy','product_title'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'return_settlements_kind_check') THEN
    ALTER TABLE parts_store.return_settlements ADD CONSTRAINT return_settlements_kind_check CHECK (kind IN ('stripe_refund','twint_refund','invoice_credit'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'return_settlements_status_check') THEN
    ALTER TABLE parts_store.return_settlements ADD CONSTRAINT return_settlements_status_check CHECK (status IN ('pending','succeeded','failed'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'customer_credit_notes_status_check') THEN
    ALTER TABLE parts_store.customer_credit_notes ADD CONSTRAINT customer_credit_notes_status_check CHECK (status IN ('issued','void'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'return_item_dispositions_disposition_check') THEN
    ALTER TABLE parts_store.return_item_dispositions ADD CONSTRAINT return_item_dispositions_disposition_check CHECK (disposition IN ('restock','quarantine','writeoff'));
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'return_stock_movements_kind_check') THEN
    ALTER TABLE parts_store.return_stock_movements ADD CONSTRAINT return_stock_movements_kind_check CHECK (kind = 'restock');
  END IF;
END $$;
