-- Additive repair for development databases that already applied 0005.
CREATE SCHEMA IF NOT EXISTS parts_store;

CREATE TABLE IF NOT EXISTS parts_store.native_picqer_order_snapshots (
  native_order_id varchar(80) PRIMARY KEY,
  event_id varchar(190) NOT NULL UNIQUE,
  content_hash char(64) NOT NULL,
  order_created_at timestamptz NOT NULL,
  snapshot_json jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS parts_store.native_picqer_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  native_order_id varchar(80) NOT NULL,
  event_id varchar(190) NOT NULL UNIQUE,
  content_hash char(64) NOT NULL,
  order_created_at timestamptz NOT NULL,
  snapshot_json jsonb NOT NULL,
  status varchar(20) NOT NULL DEFAULT 'pending',
  attempts integer NOT NULL DEFAULT 0,
  next_attempt_at timestamptz NOT NULL DEFAULT now(),
  locked_owner varchar(64),
  locked_until timestamptz,
  last_error varchar(500),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (native_order_id, content_hash)
);

CREATE INDEX IF NOT EXISTS native_relay_ready
  ON parts_store.native_picqer_outbox(status, next_attempt_at, locked_until);

DO $$ BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'return_settlements_kind_check'
      AND conrelid = 'parts_store.return_settlements'::regclass
  ) THEN
    ALTER TABLE parts_store.return_settlements
      DROP CONSTRAINT return_settlements_kind_check;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'return_settlements_kind_check'
      AND conrelid = 'parts_store.return_settlements'::regclass
  ) THEN
    ALTER TABLE parts_store.return_settlements
      ADD CONSTRAINT return_settlements_kind_check
      CHECK (kind IN ('stripe_refund', 'twint_refund', 'invoice_credit'));
  END IF;
END $$;

-- customer_groups (including its default id=1 row) is promoted as initial
-- data separately; this migration intentionally performs schema work only.