import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import crypto from "node:crypto";
import pg from "pg";

const secret = process.env.NATIVE_MEDIA_BRIDGE_SECRET;
if (!secret) throw new Error("NATIVE_MEDIA_BRIDGE_SECRET is required");
if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required");
if (process.env.REPLIT_DEPLOYMENT === "1") throw new Error("This integration test is forbidden in deployments.");

const runId = crypto.randomBytes(8).toString("hex");
const databaseName = `native_media_test_${runId}`;
const sourceDatabaseUrl = new URL(process.env.DATABASE_URL);
const testDatabaseUrl = new URL(sourceDatabaseUrl);
testDatabaseUrl.pathname = `/${databaseName}`;
const privateRoot = `${process.env.PRIVATE_OBJECT_DIR?.replace(/\/$/, "")}/integration-tests/${runId}`;
const publicRoot = `${process.env.PUBLIC_OBJECT_SEARCH_PATHS?.split(",")[0]?.trim().replace(/\/$/, "")}/integration-tests/${runId}`;
if (!privateRoot.startsWith("/") || !publicRoot.startsWith("/") || privateRoot.includes("undefined") || publicRoot.includes("undefined")) {
  throw new Error("Object storage roots are required.");
}

const admin = new pg.Client({ connectionString: sourceDatabaseUrl.toString() });
await admin.connect();
const { rows: [databaseIdentity] } = await admin.query(
  "SELECT current_database() db, (SELECT rolcreatedb FROM pg_roles WHERE rolname=current_user) createdb",
);
if (!databaseIdentity.createdb) {
  await admin.end();
  throw new Error("A disposable database cannot be created; refusing to touch the configured database.");
}
await admin.query(`CREATE DATABASE ${databaseName}`);
const pool = new pg.Pool({ connectionString: testDatabaseUrl.toString() });
await pool.query(`
  CREATE SCHEMA parts_store;
  CREATE TABLE parts_store.products (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku varchar(190) NOT NULL,
    name varchar(500) NOT NULL,
    description text NOT NULL,
    quality varchar(100) NOT NULL DEFAULT '',
    stock integer NOT NULL DEFAULT 0,
    list_price_cents integer NOT NULL DEFAULT 0,
    image_url varchar(500) NOT NULL DEFAULT '',
    image_review_required boolean NOT NULL DEFAULT false,
    featured boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true
  );
  CREATE TABLE parts_store.images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id integer NOT NULL REFERENCES parts_store.products(id),
    url varchar(500) NOT NULL,
    variants jsonb NOT NULL,
    original_path varchar(500) NOT NULL,
    original_object text,
    media_storage text NOT NULL DEFAULT 'filesystem',
    mime_type text,
    byte_size integer
  );
  CREATE TABLE parts_store.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    action varchar(100) NOT NULL,
    entity varchar(100) NOT NULL,
    entity_id integer NOT NULL,
    details jsonb NOT NULL
  );
  CREATE TABLE parts_store.native_media_events (
    event_id text PRIMARY KEY,
    content_hash text NOT NULL,
    completed_at timestamptz
  );
`);

const port = 19000 + crypto.randomInt(1000);
const API = `http://127.0.0.1:${port}/api`;
const server = spawn(process.execPath, ["--enable-source-maps", "./dist/index.mjs"], {
  cwd: new URL("..", import.meta.url),
  env: {
    ...process.env,
    NODE_ENV: "production",
    PORT: String(port),
    DATABASE_URL: testDatabaseUrl.toString(),
    PRIVATE_OBJECT_DIR: privateRoot,
    PUBLIC_OBJECT_SEARCH_PATHS: publicRoot,
  },
  stdio: ["ignore", "ignore", "pipe"],
});
let serverError = "";
server.stderr.on("data", (chunk) => { serverError += chunk.toString(); });
for (let attempt = 0; attempt < 100; attempt += 1) {
  if (server.exitCode !== null) throw new Error(`Isolated API server exited early: ${serverError}`);
  try {
    const ready = await fetch(`${API}/healthz`);
    if (ready.status < 500) break;
  } catch {}
  if (attempt === 99) throw new Error(`Isolated API server did not start: ${serverError}`);
  await new Promise((resolve) => setTimeout(resolve, 100));
}
const productIds = [];
const eventIds = [];
let originalObject = "";
let publicObjects = [];
const expectedPublicBytes = new Map();

function signedHeaders(body, eventId, contentType, path) {
  const timestamp = String(Math.floor(Date.now() / 1000));
  return signedHeadersAt(body, eventId, contentType, timestamp, path);
}

function signedHeadersAt(body, eventId, contentType, timestamp, path) {
  const signature = crypto.createHmac("sha256", secret)
    .update(`v1.${timestamp}.${eventId}.POST /api${path}.`).update(body).digest("hex");
  return {
    "Content-Type": contentType,
    "X-Ferry-Media-Timestamp": timestamp,
    "X-Ferry-Media-Event-Id": eventId,
    "X-Ferry-Media-Signature": signature,
  };
}

async function rejectedNativeRequest(path, body, headers, expectedStatus) {
  const response = await fetch(`${API}${path}`, {
    method: "POST",
    headers,
    body,
  });
  const json = await response.json();
  assert.equal(response.status, expectedStatus, `unexpected response: ${JSON.stringify(json)}`);
  return json;
}

async function nativeRequest(method, path, body, contentType, requestedEventId) {
  const eventId = requestedEventId ?? `photo-hide-${crypto.randomUUID()}`;
  eventIds.push(eventId);
  const response = await fetch(`${API}${path}`, {
    method,
    headers: signedHeaders(body, eventId, contentType, path),
    body,
  });
  const json = await response.json();
  assert.ok(response.ok, `${method} ${path} failed (${response.status}): ${JSON.stringify(json)}`);
  return json;
}

async function nativeRequestResponse(method, path, body, contentType) {
  const eventId = `photo-cleanup-${crypto.randomUUID()}`;
  eventIds.push(eventId);
  const response = await fetch(`${API}${path}`, {
    method,
    headers: signedHeaders(body, eventId, contentType, path),
    body,
  });
  return { response, json: await response.json() };
}

async function objectRequest(root, relativePath, method = "GET", body) {
  const fullPath = `${root.replace(/\/$/, "")}/native-media/${relativePath}`;
  const [, bucketName, ...objectName] = fullPath.split("/");
  const signed = await fetch("http://127.0.0.1:1106/object-storage/signed-object-url", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      bucket_name: bucketName,
      object_name: objectName.join("/"),
      method,
      expires_at: new Date(Date.now() + 60_000).toISOString(),
    }),
  });
  assert.ok(signed.ok, `could not sign ${method} for stored object`);
  return fetch((await signed.json()).signed_url, {
    method,
    body,
    headers: body ? { "Content-Type": "image/png" } : undefined,
  });
}

async function captureState(productId, imageId) {
  const { rows: [product] } = await pool.query(
    "SELECT image_url,image_review_required FROM parts_store.products WHERE id=$1",
    [productId],
  );
  const { rows: images } = await pool.query(
    "SELECT id,product_id,url,variants,original_path,original_object,media_storage,mime_type,byte_size FROM parts_store.images WHERE id=$1",
    [imageId],
  );
  const original = await objectRequest(privateRoot, originalObject);
  assert.ok(original.ok, "private original fixture is missing");
  const objects = [[originalObject, Buffer.from(await original.arrayBuffer())]];
  for (const objectPath of publicObjects) {
    const variant = await objectRequest(publicRoot, objectPath);
    assert.ok(variant.ok, `public variant fixture ${objectPath} is missing`);
    objects.push([objectPath, Buffer.from(await variant.arrayBuffer())]);
  }
  return { product, images, objects };
}

async function assertStateUnchanged(before, productId, imageId, label) {
  const after = await captureState(productId, imageId);
  assert.deepEqual(after.product, before.product, `${label}: product changed`);
  assert.deepEqual(after.images, before.images, `${label}: image link changed`);
  assert.deepEqual(after.objects, before.objects, `${label}: object bytes changed`);
}

try {
  const suffix = crypto.randomUUID();
  const sku = `BRIDGE-PHOTO-${suffix}`;
  const reason = "The pictured connector does not match this SKU.";
  const token = crypto.randomBytes(16).toString("hex");
  const bytes = Buffer.from(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
    "base64",
  );
  const { rows: [product] } = await pool.query(
    `INSERT INTO parts_store.products(sku,name,description,quality,stock,list_price_cents,image_url,featured,active)
     VALUES($1,'Native media hide fixture','Integration fixture','test',1,1,'',false,true) RETURNING id`,
    [sku],
  );
  productIds.push(product.id);
  originalObject = `${product.id}/${token}/original.png`;
  publicObjects = [320, 640, 1280].map((width) => `${product.id}/${token}/${width}w.webp`);
  const variants = Object.fromEntries(publicObjects.map((path) => {
    const width = path.match(/\/(\d+)w\.webp$/)[1];
    return [width, `/api/storage/public-objects/native-media/${path}`];
  }));
  const oldUrl = variants["1280"];
  assert.ok((await objectRequest(privateRoot, originalObject, "PUT", bytes)).ok,
    "could not create private original fixture");
  for (const objectPath of publicObjects) {
    const width = objectPath.match(/\/(\d+)w\.webp$/)[1];
    const variantBytes = Buffer.concat([bytes, Buffer.from(`variant-${width}`)]);
    expectedPublicBytes.set(objectPath, variantBytes);
    assert.ok((await objectRequest(publicRoot, objectPath, "PUT", variantBytes)).ok,
      `could not create public variant fixture ${objectPath}`);
  }
  await pool.query("UPDATE parts_store.products SET image_url=$1 WHERE id=$2", [oldUrl, product.id]);

  const { rows: [image] } = await pool.query(
    `INSERT INTO parts_store.images(product_id,url,variants,original_path,original_object,media_storage,mime_type,byte_size)
     VALUES($1,$2,$3::jsonb,$4::varchar,$4::text,'object_storage','image/png',$5) RETURNING id,url`,
    [product.id, oldUrl, JSON.stringify(variants), originalObject, bytes.length],
  );

  const staffId = 987654;
  const hidePath = `/native/media/products/${product.id}/images/hide`;
  const hideBody = Buffer.from(JSON.stringify({ image_id: image.id, url: oldUrl, reason, staff_id: staffId }));
  const unchanged = await captureState(product.id, image.id);

  const { rows: [sharedCoverProduct] } = await pool.query(
    `INSERT INTO parts_store.products(sku,name,description,quality,stock,list_price_cents,image_url,featured,active)
     VALUES($1,'Shared cover target','Integration fixture','test',1,1,$2,false,true) RETURNING id`,
    [`BRIDGE-PHOTO-SHARED-${suffix}`, oldUrl],
  );
  productIds.push(sharedCoverProduct.id);
  const redirectedEventId = `photo-hide-redirect-${crypto.randomUUID()}`;
  eventIds.push(redirectedEventId);
  const coverBody = Buffer.from(JSON.stringify({ image_id: null, url: oldUrl, reason, staff_id: staffId }));
  const redirectedPath = `/native/media/products/${sharedCoverProduct.id}/images/hide`;
  await rejectedNativeRequest(
    redirectedPath,
    coverBody,
    signedHeaders(coverBody, redirectedEventId, "application/json", hidePath),
    403,
  );
  const { rows: [sharedCoverAfter] } = await pool.query(
    "SELECT image_url,image_review_required FROM parts_store.products WHERE id=$1",
    [sharedCoverProduct.id],
  );
  assert.deepEqual(sharedCoverAfter, { image_url: oldUrl, image_review_required: false });
  await assertStateUnchanged(unchanged, product.id, image.id, "signature redirected to another product");

  const missingEventId = `photo-hide-missing-${crypto.randomUUID()}`;
  eventIds.push(missingEventId);
  const missingHeaders = signedHeaders(hideBody, missingEventId, "application/json", hidePath);
  delete missingHeaders["X-Ferry-Media-Signature"];
  await rejectedNativeRequest(hidePath, hideBody, missingHeaders, 403);
  await assertStateUnchanged(unchanged, product.id, image.id, "missing signature");

  const invalidEventId = `photo-hide-invalid-${crypto.randomUUID()}`;
  eventIds.push(invalidEventId);
  const invalidHeaders = signedHeaders(hideBody, invalidEventId, "application/json", hidePath);
  invalidHeaders["X-Ferry-Media-Signature"] = "0".repeat(64);
  await rejectedNativeRequest(hidePath, hideBody, invalidHeaders, 403);
  await assertStateUnchanged(unchanged, product.id, image.id, "invalid signature");

  const expiredEventId = `photo-hide-expired-${crypto.randomUUID()}`;
  eventIds.push(expiredEventId);
  const expiredTimestamp = String(Math.floor(Date.now() / 1000) - 301);
  await rejectedNativeRequest(
    hidePath,
    hideBody,
    signedHeadersAt(hideBody, expiredEventId, "application/json", expiredTimestamp, hidePath),
    403,
  );
  await assertStateUnchanged(unchanged, product.id, image.id, "expired signature");

  const conflictEventId = `photo-hide-conflict-${crypto.randomUUID()}`;
  eventIds.push(conflictEventId);
  const retryableBody = Buffer.from(JSON.stringify({ image_id: image.id + 1_000_000, url: oldUrl, reason, staff_id: staffId }));
  await rejectedNativeRequest(hidePath, retryableBody, signedHeaders(retryableBody, conflictEventId, "application/json", hidePath), 409);
  await assertStateUnchanged(unchanged, product.id, image.id, "retryable failed request");
  const changedBody = Buffer.from(JSON.stringify({ image_id: image.id, url: oldUrl, reason: `${reason} changed`, staff_id: staffId }));
  await rejectedNativeRequest(hidePath, changedBody, signedHeaders(changedBody, conflictEventId, "application/json", hidePath), 409);
  await assertStateUnchanged(unchanged, product.id, image.id, "event id with changed content");
  console.log("PASS rejected bridge hide requests preserve product, image and object bytes");

  const completedEventId = `photo-hide-completed-${crypto.randomUUID()}`;
  const completedHeaders = signedHeaders(hideBody, completedEventId, "application/json", hidePath);
  const hidden = await nativeRequest(
    "POST",
    hidePath,
    hideBody,
    "application/json",
    completedEventId,
  );
  assert.deepEqual(hidden, { hidden: true, product_id: product.id });

  const { rows: [after] } = await pool.query(
    "SELECT image_url,image_review_required FROM parts_store.products WHERE id=$1",
    [product.id],
  );
  assert.equal(after.image_url, "");
  assert.equal(after.image_review_required, true);
  assert.equal(Number((await pool.query("SELECT COUNT(*) count FROM parts_store.images WHERE id=$1", [image.id])).rows[0].count), 0);

  const replayState = {
    product: after,
    imageCount: Number((await pool.query("SELECT COUNT(*) count FROM parts_store.images WHERE id=$1", [image.id])).rows[0].count),
    auditCount: Number((await pool.query("SELECT COUNT(*) count FROM parts_store.audit_events WHERE entity='product' AND entity_id=$1", [product.id])).rows[0].count),
  };
  await rejectedNativeRequest(hidePath, hideBody, completedHeaders, 409);
  const { rows: [productAfterReplay] } = await pool.query(
    "SELECT image_url,image_review_required FROM parts_store.products WHERE id=$1",
    [product.id],
  );
  assert.deepEqual(productAfterReplay, replayState.product, "replay changed the product");
  assert.equal(Number((await pool.query("SELECT COUNT(*) count FROM parts_store.images WHERE id=$1", [image.id])).rows[0].count), replayState.imageCount);
  assert.equal(Number((await pool.query("SELECT COUNT(*) count FROM parts_store.audit_events WHERE entity='product' AND entity_id=$1", [product.id])).rows[0].count), replayState.auditCount);

  const original = await objectRequest(privateRoot, originalObject);
  assert.ok(original.ok, "the private original object is no longer reachable");
  assert.deepEqual(Buffer.from(await original.arrayBuffer()), bytes, "the private original bytes changed");
  for (const objectPath of publicObjects) {
    const variant = await objectRequest(publicRoot, objectPath);
    assert.ok(variant.ok, `public variant ${objectPath} is no longer reachable`);
    assert.deepEqual(
      Buffer.from(await variant.arrayBuffer()),
      expectedPublicBytes.get(objectPath),
      `public variant ${objectPath} changed`,
    );
  }

  const { rows: [audit] } = await pool.query(
    `SELECT user_id,details FROM parts_store.audit_events
     WHERE action='image.incorrect_unlinked' AND entity='product' AND entity_id=$1 ORDER BY id DESC LIMIT 1`,
    [product.id],
  );
  assert.equal(Number(audit.user_id), staffId);
  assert.deepEqual(audit.details, {
    product_id: product.id,
    sku,
    old_url: oldUrl,
    reason,
    by: staffId,
    shared_references: { images: 0, products: 1 },
    detached_media: { original: originalObject, variants },
  });

  const { rows: [sharedProduct] } = await pool.query(
    `INSERT INTO parts_store.products(sku,name,description,quality,stock,list_price_cents,image_url,featured,active)
     VALUES($1,'Shared media fixture','Integration fixture','test',1,1,$2,false,true) RETURNING id`,
    [`SHARED-${suffix}`, oldUrl],
  );
  productIds.push(sharedProduct.id);
  const { rows: [sharedImage] } = await pool.query(
    `INSERT INTO parts_store.images(product_id,url,variants,original_path,original_object,media_storage,mime_type,byte_size)
     VALUES($1,$2,$3::jsonb,$4::varchar,$4::text,'object_storage','image/png',$5) RETURNING id`,
    [sharedProduct.id, oldUrl, JSON.stringify(variants), originalObject, bytes.length],
  );
  const confirmation = Buffer.from(JSON.stringify({ confirm: "DELETE ORPHANED MEDIA", staff_id: staffId }));
  const { rows: [unlinkAudit] } = await pool.query(
    `SELECT id FROM parts_store.audit_events WHERE action='image.incorrect_unlinked' AND entity_id=$1 ORDER BY id DESC LIMIT 1`,
    [product.id],
  );
  const protectedAttempt = await nativeRequestResponse(
    "POST", `/native/media/orphans/${unlinkAudit.id}/delete`, confirmation, "application/json",
  );
  assert.equal(protectedAttempt.response.status, 409);
  assert.match(protectedAttempt.json.error, /linked again or shared/i);
  assert.ok((await objectRequest(privateRoot, originalObject)).ok, "shared original was deleted");
  for (const objectPath of publicObjects) {
    assert.ok((await objectRequest(publicRoot, objectPath)).ok, `shared variant ${objectPath} was deleted`);
  }

  await pool.query("DELETE FROM parts_store.images WHERE id=$1", [sharedImage.id]);
  await pool.query("UPDATE parts_store.products SET image_url='' WHERE id=$1", [sharedProduct.id]);
  await pool.query("UPDATE parts_store.products SET image_url='' WHERE id=$1", [sharedCoverProduct.id]);
  const deleted = await nativeRequest(
    "POST", `/native/media/orphans/${unlinkAudit.id}/delete`, confirmation, "application/json",
  );
  assert.equal(deleted.deleted, true);
  assert.equal(Number(deleted.source_audit_id), Number(unlinkAudit.id));
  assert.equal((await objectRequest(privateRoot, originalObject)).status, 404);
  for (const objectPath of publicObjects) {
    assert.equal((await objectRequest(publicRoot, objectPath)).status, 404);
  }
  const { rows: [cleanupAudit] } = await pool.query(
    `SELECT user_id,details FROM parts_store.audit_events
     WHERE action='image.orphan_deleted' AND entity_id=$1 ORDER BY id DESC LIMIT 1`,
    [product.id],
  );
  assert.equal(Number(cleanupAudit.user_id), staffId);
  assert.equal(Number(cleanupAudit.details.source_audit_id), Number(unlinkAudit.id));
  console.log("PASS orphan cleanup deletes unreferenced bytes and protects shared bytes");
} finally {
  if (productIds.length) {
    await pool.query("DELETE FROM parts_store.audit_events WHERE entity='product' AND entity_id=ANY($1::int[])", [productIds]);
    await pool.query("DELETE FROM parts_store.images WHERE product_id=ANY($1::int[])", [productIds]);
    await pool.query("DELETE FROM parts_store.products WHERE id=ANY($1::int[])", [productIds]);
  }
  for (const eventId of eventIds) await pool.query("DELETE FROM parts_store.native_media_events WHERE event_id=$1", [eventId]);
  if (originalObject) await objectRequest(privateRoot, originalObject, "DELETE").catch(() => {});
  for (const objectPath of publicObjects) {
    await objectRequest(publicRoot, objectPath, "DELETE").catch(() => {});
  }
  await pool.end();
  server.kill("SIGTERM");
  await new Promise((resolve) => server.once("exit", resolve));
  await admin.query(`DROP DATABASE ${databaseName} WITH (FORCE)`);
  await admin.end();
}