CREATE TABLE IF NOT EXISTS invoice_accounting (
 order_id INT UNSIGNED PRIMARY KEY,verified TINYINT(1) NOT NULL DEFAULT 0,due_date DATE NULL,
 paid_cents BIGINT UNSIGNED NOT NULL DEFAULT 0,note TEXT NOT NULL,version INT UNSIGNED NOT NULL DEFAULT 0,
 updated_by INT UNSIGNED NOT NULL,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(order_id) REFERENCES orders(id),FOREIGN KEY(updated_by) REFERENCES users(id),
 INDEX(due_date),INDEX(verified)
) ENGINE=InnoDB;