-- BuyBack has been retired. Preserve unrelated audit history while removing
-- every audit event generated by the retired feature before its tables go away.
DELETE FROM audit_events
WHERE LOWER(action) LIKE 'buyback%'
   OR LOWER(entity) LIKE 'buyback%';

DROP TABLE IF EXISTS buyback_requests;
DROP TABLE IF EXISTS buyback_items;